sudo: required
services:
    - docker 
before_install:
    - docker build -t osamahamdini/docker-react -f Dockerfile.dev .
script:
    - docker run osamahamdini/docker-react npm run test -- --coverage